apiVersion: v1
kind: ConfigMap
metadata: 
  name: prometheus-yaml-config
data:
  prometheus.yml: | 
{{ if eq .Values.prometheusConfigType "Simple" }}
    scrape_configs:
      - job_name: {{ .Values.prometheus.job_name }}
        scrape_interval: {{ .Values.prometheus.scrape_interval }}
        scrape_timeout: {{ .Values.prometheus.scrape_timeout }}
        static_configs:
        - targets: 
{{ .Values.prometheus.targets | toYaml | indent 10 }}
{{ else }}
{{ .Values.prometheusValues | toYaml | indent 4 }}
{{ end }}